#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

apt-get -y update
apt-get -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
