#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

apt-get -y update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		rewrite ^ https://github.com/IK-18 permanent;
	}
	location / {
		try_files \$uri \$uri/ =404;
	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
