#!/usr/bin/env bash
# Install and configure HAproxy on server


sudo apt update
sudo apt-get install -y nginx
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

echo "server {
        listen 80;
        server_name _;

        location / {
                proxy_pass http://localhost:8080;
        }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
echo "frontend http_front
        bind *:8080
        default_backend backend_servers

backend backend_servers
        balance roundrobin
        server server1 18.210.16.13:80 check
        server server2 18.204.7.67:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
if [ "$(pgrep -c haproxy)" -le 0 ]; then
        service haproxy start
else
        service haproxy restart
fi
