#!/usr/bin/env bash
# generates a tar-gzipped archive of the backup file
if [$# -eq 0 ]; then
	echo "Usage: ./5-mysql_backup PASSWORD"
	exit 1
fi

mysqldump -uroot -p"$1" --all-databases > backup.sql

tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
