#!/usr/bin/env bash
# This script displays To infinty and beyond indefinitely

delete() {
	rm /var/run/myscript.pid
	exit
}

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && delete' SIGTERM
	trap 'delete' SIGQUIT
done
